# Generated by Django 3.0.5 on 2020-04-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('pro_key', models.CharField(max_length=32, null=True)),
                ('pro_script', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dev_name', models.CharField(max_length=32, null=True)),
                ('dev_address', models.CharField(max_length=32, null=True)),
                ('dev_script', models.CharField(max_length=32, null=True)),
                ('accuracy', models.CharField(max_length=32, null=True)),
                ('latitude', models.CharField(max_length=32, null=True)),
                ('imei', models.CharField(max_length=15, null=True)),
                ('cpu_id', models.CharField(max_length=8, null=True)),
                ('dev_id_key', models.CharField(max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('site_script', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=16, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间')),
                ('devid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Register')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Site'),
        ),
        migrations.AddField(
            model_name='product',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tmp', models.IntegerField(null=True)),
                ('hum', models.IntegerField(null=True)),
                ('pm10', models.IntegerField(null=True)),
                ('pm25', models.IntegerField(null=True)),
                ('last_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Register')),
            ],
        ),
    ]
