# Generated by Django 2.1 on 2020-03-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200319_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_key', models.CharField(max_length=32, null=True)),
                ('dev_id_key', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_key', models.CharField(max_length=32)),
                ('pro_script', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('avatar', models.FileField(default='static/img/default.jpg', upload_to='avatar/')),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='time',
        ),
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.AddField(
            model_name='data',
            name='last_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='register',
            name='accuracy_latitude',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='cpu_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='register',
            name='dev_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='dev_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='imei',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Register'),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='state',
            name='devid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Register'),
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Site'),
        ),
        migrations.AddField(
            model_name='password',
            name='dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Register'),
        ),
    ]
