# Generated by Django 2.1 on 2020-03-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200322_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间'),
        ),
    ]
