# Generated by Django 2.1 on 2020-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200324_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='dev',
        ),
        migrations.AddField(
            model_name='register',
            name='dev_id_key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='dev_script',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
