# Generated by Django 2.1 on 2020-03-31 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200324_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='accuracy_latitude',
            new_name='accuracy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='site',
        ),
        migrations.AddField(
            model_name='product',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='register',
            name='latitude',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Product'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_script',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_script',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='cpu_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='imei',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
